### ISSUE TITLE
Travis CI 無法正確 Cache

### ISSUE THREAD

**Issue by elct9620** [5xRuby/spgateway-rails#1]
https://github.com/5xRuby/spgateway-rails/blob/master/.travis.yml#L15

在沒有特殊情況下 Travis CI 會自動設定，如果這樣設定的話反而會讓 Travis CI 無法自動指定正確的 gem 安裝目錄。

**Comment by zetavg** [comment]
之前因為一直卡在預設的 gem install

```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```

的問題還沒研究出原因，所以就先蓋掉預設的指令讓他動（繼續研究中 .__.

**Comment by elct9620** [comment]
因為你把 Gemfile.lock 刪掉的關係⋯⋯

我今天設定這樣就沒問題
https://github.com/elct9620/rails-letsencrypt/blob/master/.travis.yml

**Comment by zetavg** [comment]
其實不是，上面會把 `Gemfile.lock` 刪掉就是為了解決這個問題 XD

剛剛找到原因了，因為我之前把 `rspec-rails`直接寫在 `Gemfile` 裡，所以 appraise 產生的 gemfiles 通通重新指定了一個 `rspec-rails`。剛剛重跑 `appraisal install` 就解決了 🎉

**Comment by elct9620** [comment]
喔喔，如果有改 Appraisal 或者 Gemfile  要跑過 appraisal 阿，不用下 install

**Comment by elct9620** [comment]
其實是早上覺得麻煩複製了這邊的設定，結果發現怪怪的（被拖走

**Comment by zetavg** [comment]
剛好都在包 gem，這點其實蠻方便的 www
