### ISSUE TITLE
在 config.payment_code_callback 中，更新 controller.flash 之後 flash message 沒有顯示出來

### ISSUE THREAD

**Issue by zetavg** [5xRuby/spgateway-rails#2]
若照著 [README 寫的設定方式](https://github.com/5xRuby/spgateway-rails#get-the-customers-atm-transfer-account-or-payment-code-and-show-them-on-your-website-with-payment_code_callback)，flash message 在最後 redirect 之後就會消失不見，無法被顯示出來。

**Comment by zetavg** [comment]
發現在 `Spgateway::Engine` 裡，controller 中拿到的 `session` 都不太正常，都是一個空 Hash (`{}`) 而不是 `ActionDispatch::Request::Session`，可能是此問題肇因。

另外已經發現在 39fd78d 之前都是正常的，正在一步步倒帶回去尋找是哪個 commit 之後發生問題。

**Comment by zetavg** [comment]
發現是從 0feca68 就開始出現 `config.mpg_callback` 裡的 `controller.request.session` 是空 Hash 的問題。

**Comment by elct9620** [comment]
https://stackoverflow.com/questions/30582318/what-is-the-difference-between-null-session-and-reset-session-in-rails-4

> null_session should be used in API-style controllers, where you have no use for the session object.

https://github.com/5xRuby/spgateway-rails/blob/master/app/controllers/spgateway/application_controller.rb#L4

**Comment by elct9620** [comment]
看起來不是 `null_session` 的問題，預設的時候這個似乎都開著。

功能是在沒有 Session 的時候自動補上空的 Session，但是也有可能是因為這樣被補上空的 Hash

**Comment by zetavg** [comment]
剛剛為了重現問題，在 dummy app 裡補上驗證 flash message 有沒有顯示出來的 feature spec，結果發現在 dummy app 裡面是正常的（驚），另外 `controller.request.session` 也是看起來正常的 `#<ActionDispatch::Request::Session:0x7faa25ecf488 not yet loaded>`。

**Comment by elct9620** [comment]
這樣也許是 Rails 設定上有問題而不是 Gem 方面的，跟昨天推測的情況比較接近。

**Comment by zetavg** [comment]
不過把 gem 的版本倒回去之後是可以解決這個問題，而且 @akiicat 串接到官網上之後確實也遇到一樣的狀況 (抓頭

**Comment by elct9620** [comment]
目前暫時沒有辦法幫忙檢查，之後有時間還沒修好我再來圍觀吧（望

**Comment by zetavg** [comment]
發現了 https://github.com/5xRuby/spgateway-rails/commit/0feca6825d0eb997da6b3a14f0c965e1d6da4260#diff-c458919ad307740d7f244992c9e13e57R2，  
（原本沒有 `require_dependency 'spgateway/application_controller'`）  
所以在 0feca68 之前，`ActionController::Base` 都不是 gem 的 `ActionController::Base`，`protect_from_forgery with: :null_session` 應該都沒有生效。

**Comment by zetavg** [comment]
為了不讓蒼時大大早死， @elct9620 我想你還是有時間而且我修好之後再來圍觀吧 (雖然目前是知道要修哪了) XD
